services:
  verdaccio:
    build:
      context: ./docker/verdaccio
    container_name: tp-cd-deployment-verdaccio
    volumes:
      - verdaccio-storage:/verdaccio/storage
    networks:
      - cd-network
    ports:
      - "4873:4873"

  registry:
    image: registry:2
    container_name: tp-cd-deployment-registry
    volumes:
      - registry-storage:/var/lib/registry
    networks:
      - cd-network
    ports:
      - "5000:5000"
  ssh-npm-target:
    build:
      context: ./docker/ssh-target
    container_name: tp-cd-deployment-ssh-npm-target
    depends_on:
      - verdaccio
    networks:
      - cd-network

  ssh-docker-target:
    build:
      context: ./docker/ssh-target
    container_name: tp-cd-deployment-ssh-docker-target
    depends_on:
      - registry
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cd-network

networks:
  cd-network:
    driver: bridge

volumes:
  verdaccio-storage:
  registry-storage:
